[package]
name = "tool-click"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
bitflags = "2.4"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.39", features = ["macros", "rt"] }
tokio-util = { version = "0.7" }
tracing = "0.1"
url = "2.5"

soulbrowser-core-types = { path = "../core-types", features = ["serde-full"] }
perceiver-structural = { path = "../perceiver-structural" }

[dev-dependencies]
tokio = { version = "1.39", features = ["macros", "rt", "rt-multi-thread"] }
