[package]
name = "tool-select-option"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
perceiver-structural = { path = "../perceiver-structural" }
serde = { version = "1.0", features = ["derive"] }
soulbrowser-core-types = { path = "../core-types", features = ["serde-full"] }
thiserror = "1.0"
tokio = { version = "1.39", features = ["macros", "rt"] }
tokio-util = "0.7"
tracing = "0.1"
url = "2.5"

[dev-dependencies]
tokio = { version = "1.39", features = ["macros", "rt", "rt-multi-thread"] }
serde_json = "1.0"
