global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:
  - job_name: 'soulbrowser'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - 'host.docker.internal:9090'
        labels:
          service: soulbrowser
